version: '2'
services:
  unms:
    image: oznu/unms:latest
    restart: always
    expose:
      - 443
      - 80
    networks:
      - web
    ports:
      - 2055:2055/udp
    environment:
      - TZ=America/New_York
    volumes:
      - data:/config
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:unms.brooks.network"

volumes:
  data:

networks:
  web:
    external: true
