version: '2'
services:
  unms:
    image: oznu/unms:latest
    container_name: unms
    restart: always
    ports:
      - 8444:443
      - 8480:80
      - 2055:2055/udp
    environment:
      - TZ=America/New_York
    volumes:
      - data:/config

volumes:
  data:
