---
- name: Import ClearLinux common tasks
  import_tasks: clear_linux.yml
  when: ansible_distribution == 'ClearLiux'

- name: Import Debian-based common tasks
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian'
