version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - config:/etc/prometheus
      - data:/prometheus

volumes:
  config:
  data:
