version: '3'
services:
  grafana:
    container_name: grafana
    restart: always
    expose:
      - 3000
    volumes:
      - data:/var/lib/grafana
      - config:/etc/grafana
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=graphs.brooks.network
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=graphs.brooks.network
      - LETSENCRYPT_EMAIL=bswinnerton@gmail.com
    image: grafana/grafana

volumes:
  data:
  config:

networks:
  default:
    external:
      name: nginx-proxy_default
