---
# libvirt-guests is a tool that will auto shut down KVM guests before the host
# is shut down.
- name: Enable libvirt-guests
  become: true
  systemd:
    name: libvirt-guests
    enabled: yes
    state: started
