version: '3'
services:
  lounge:
    image: thelounge/lounge:latest
    container_name: thelounge
    restart: always
    ports:
      - 9000:9000
    volumes:
      - data:/home/lounge/data
    environment:
      - VIRTUAL_HOST=irc.brooks.network
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=irc.brooks.network
      - LETSENCRYPT_EMAIL=bswinnerton@gmail.com

volumes:
  data:

networks:
  default:
    external:
      name: nginx-proxy_default
