---
- name: disable Docker to start on boot
  when: ansible_distribution == 'ClearLinux'
  service:
    name: docker
    enabled: no

- name: enable Docker to start on boot
  when: ansible_distribution == 'ClearLinux'
  service:
    name: docker
    enabled: yes
