version: '3'
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
    expose:
      - 80
      - 443
    environment:
      TZ: 'America/New_York'
    volumes:
      - 'data:/etc/pihole/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:pihole.brooks.network"

volumes:
  data:
