---
- name: install KVM kernel
  become: yes
  package:
    name: kernel-kvm

- name: install KVM bundle
  become: yes
  package:
    name: kvm-host

- name: add main account to KVM group
  become: yes
  user:
    name: brooks
    groups: kvm
    append: yes

- name: enable libvirtd
  become: yes
  service:
    name: libvirtd
    enabled: yes
    state: started

- name: create br0 netdev
  become: yes
  template:
    src: br0.netdev.j2
    dest: /etc/systemd/network/br0.netdev
    owner: root
    group: root
    mode: 0644

- name: create br0 network
  become: yes
  copy:
    src: br0.network
    dest: /etc/systemd/network/br0.network
    owner: root
    group: root
    mode: 0644

- name: associate physical interface with bridge
  become: yes
  copy:
    src: 80-dhcp.network
    dest: /etc/systemd/network/80-dhcp.network
    owner: root
    group: root
    mode: 0644

- name: update kernel bridge module
  become: yes
  copy:
    src: 90-bridge.conf
    dest: /etc/sysctl.d/90-bridge.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd-networkd

- name: determine defined vms
  become: yes
  check_mode: no
  command: virsh list --name --all
  register: defined_vms

- name: determine autostarted vms
  become: yes
  check_mode: no
  command: virsh list --name --autostart
  register: autostarted_vms

- name: determine started vms
  become: yes
  check_mode: no
  command: virsh list --name
  register: started_vms

- name: define vms
  become: yes
  command: "virsh define {{ item }}"
  when: "ansible_hostname not in defined_vms.stdout_lines"
  with_fileglob:
    - "kvms/hosts/{{ inventory_hostname }}/autostart/*"
    - "kvms/hosts/{{ inventory_hostname }}/zombie/*"

- name: set vms to autostart
  become: yes
  command: "virsh autostart {{ item | splitext | first }}"
  when: "ansible_hostname not in autostarted_vms.stdout_lines"
  with_fileglob:
    - "kvms/hosts/{{ inventory_hostname }}/autostart/*"

- name: start vms
  become: yes
  command: "virsh start {{ item | splitext | first }}"
  when: "ansible_hostname not in started_vms.stdout_lines"
  with_fileglob:
    - "kvms/hosts/{{ inventory_hostname }}/autostart/*"
