---
- name: place tallow configuration in correct directory
  become: yes
  when: ansible_distribution == 'ClearLinux'
  copy:
    src: tallow.conf
    dest: /etc/tallow.conf
    owner: root
    group: root
    mode: 0644
  notify: restart tallow
