all:
  children:
    bare-metal:
      hosts:
        pi.brooks.network:
      children:
        kvm-hosts:
          hosts:
            nuc7i5a.brooks.network:
    docker-hosts:
      hosts:
        nuc7i5a.brooks.network:
