all:
  children:
    bare-metal:
      hosts:
        pi.brooks.network:
        pi2.brooks.network:
          ansible_host: 10.0.100.151
      children:
        kvm-hosts:
          hosts:
            nuc7i5a.brooks.network:
    docker-hosts:
      hosts:
        nuc7i5a.brooks.network:
