all:
  children:
    kubernetes:
      hosts:
        kube-master-a.brooks.network:
        kube-master-b.brooks.network:
        kube-node-a1.brooks.network:
        kube-node-a2.brooks.network:
        kube-node-b1.brooks.network:
        kube-node-b2.brooks.network:
