---
- name: preflight tasks
  hosts: all
  tags: always
  roles:
    - preflight

- name: install and set up common tasks
  hosts: all
  tags: common
  roles:
    - common

- name: whitelist local IPs for Clear Linux
  hosts: clearlinux
  tags: security
  roles:
    - tallow

- name: enable libvirt-guests
  hosts: kvm-hosts
  tags: kvm
  roles:
    - libvirt-guests

- name: install Docker
  become: true
  hosts: docker-hosts
  tags: docker
  roles:
    - geerlingguy.docker

# https://github.com/clearlinux/distribution/issues/157
- name: use custom systemd Docker script for ClearLinux bug
  become: true
  hosts: docker-hosts
  tags: docker
  roles:
    - docker-systemd-service-for-clear-linux-bug

- name: install GlusterFS
  hosts: kubernetes-nodes
  tags: glusterfs
  roles:
    - glusterfs
