---
# Set up common tasks across the fleet
- name: Install and set up common tasks
  hosts: all
  roles:
    - common

# Install GlusterFS on all kubernetes nodes
- name: Install GlusterFS
  hosts: kubernetes-nodes
  roles:
    - glusterfs
