---
- name: Install and set up common tasks
  hosts: all
  tags: common
  roles:
    - common

- name: Install Docker
  become: true
  hosts: docker-hosts
  tags: docker
  roles:
    - geerlingguy.docker

- name: Install GlusterFS
  hosts: kubernetes-nodes
  tags: glusterfs
  roles:
    - glusterfs
