---
# Set up common tasks across the fleet
- name: Install and set up common tasks
  hosts: all
  roles:
    - common

# Install docker on docker hosts
- name: Install Docker
  become: true
  hosts: docker-hosts
  roles:
    - geerlingguy.docker

# Install GlusterFS on all kubernetes nodes
- name: Install GlusterFS
  hosts: kubernetes-nodes
  roles:
    - glusterfs
