---
- name: preflight tasks
  hosts: all
  tags: always
  roles:
    - preflight

- name: install and set up common tasks
  hosts: all
  tags: common
  roles:
    - common

- name: whitelist local IPs for Clear Linux
  hosts: clearlinux
  tags: security
  roles:
    - tallow

- name: set up mount points
  hosts: kvm-hosts
  tags: disk
  roles:
    - mount-points

- name: install node_exporter
  hosts: bare-metal
  tags: monitoring
  roles:
    - cloudalchemy.node-exporter

- name: enable libvirt-guests
  hosts: kvm-hosts
  tags: kvm
  roles:
    - libvirt-guests

- name: install Docker
  become: true
  hosts: docker-hosts
  tags: docker
  roles:
    - geerlingguy.docker

# https://github.com/clearlinux/distribution/issues/157
- name: use custom Docker systemd service for ClearLinux boot race condition bug
  become: true
  hosts: docker-hosts
  tags: docker
  roles:
    - clear-linux-docker-service-bugfix

- name: install GlusterFS
  hosts: kubernetes-nodes
  tags: glusterfs
  roles:
    - glusterfs
