---
- name: Install and set up common tasks
  hosts: all
  roles:
    - common

- name: Install node_exporter on all bare-metal hosts
  hosts: bare-metal
  roles:
    - ansible-node-exporter

- name: Install GlusterFS
  hosts: kubernetes-nodes
  roles:
    - glusterfs
