version: '3'
services:
  snmp-exporter:
    image: prom/snmp-exporter
    container_name: snmp_exporter
    restart: always
    ports:
      - 9116:9116
    volumes:
      - ./snmp.yml:/etc/snmp_exporter/snmp.yml
