version: '3'
services:
  unifi_exporter:
    image: bswinnerton/unifi_exporter
    container_name: unifi_exporter
    command: -config.file /etc/unifi_exporter/config.yml
    restart: always
    ports:
      - 9130:9130
    volumes:
      - config:/etc/unifi_exporter

volumes:
  config:
