version: '3'
services:
  lounge:
    image: thelounge/lounge:latest
    container_name: thelounge
    restart: always
    expose:
      - 9000
    volumes:
      - data:/home/lounge/data
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:irc.brooks.network"

volumes:
  data:

networks:
  web:
    external: true
