---
- name: place docker.service in systemd directory
  become: yes
  when: ansible_distribution == 'ClearLinux'
  copy:
    src: docker.service
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
  notify:
    - disable Docker to start on boot
    - enable Docker to start on boot
